version: '3.8'

services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
